# Generated by Django 5.0.6 on 2024-11-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tweetapp", "0002_alter_tweet_options_tweet_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweet",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
